import type { Source } from "./types";

/**
 * The newsstand shelf.
 *
 * Feed URLs move around more often than publishers admit, so every entry is
 * checked by `npm run check:sources` and the feed API quietly skips whatever is
 * down rather than failing the whole page. `level` is a reading-difficulty hint
 * for learners, not a judgement on the journalism.
 */
export const SOURCES: Source[] = [
  // ---------------------------------------------------------------- German
  {
    id: "nachrichtenleicht",
    name: "Nachrichtenleicht (Deutschlandfunk)",
    short: "Nachrichtenleicht",
    lang: "de",
    category: "learner",
    level: "easy",
    feed: "https://www.nachrichtenleicht.de/nachrichtenleicht-nachrichten-100.rss",
    site: "https://www.nachrichtenleicht.de",
    note: "News in Leichte Sprache: short sentences, one idea per line. The best starting point for A2 to B1.",
  },
  {
    id: "dw-de-top",
    name: "Deutsche Welle - Top-Themen",
    short: "DW Top",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://rss.dw.com/xml/rss-de-top",
    site: "https://www.dw.com/de",
    note: "Written for an international audience, so the vocabulary stays fair.",
  },
  {
    id: "dw-de-all",
    name: "Deutsche Welle - Alle Themen",
    short: "DW Alle",
    lang: "de",
    category: "world",
    level: "medium",
    feed: "https://rss.dw.com/rdf/rss-de-all",
    site: "https://www.dw.com/de",
  },
  {
    id: "tagesschau",
    name: "tagesschau",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://www.tagesschau.de/xml/rss2/",
    site: "https://www.tagesschau.de",
    note: "Germany's reference newscast. Clean, factual register.",
  },
  {
    id: "zdf-heute",
    name: "ZDF heute",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://www.zdf.de/rss/zdf/nachrichten",
    site: "https://www.zdf.de/nachrichten",
  },
  {
    id: "deutschlandfunk",
    name: "Deutschlandfunk Nachrichten",
    short: "DLF",
    lang: "de",
    category: "top",
    level: "hard",
    feed: "https://www.deutschlandfunk.de/nachrichten-100.rss",
    site: "https://www.deutschlandfunk.de",
  },
  {
    id: "spiegel",
    name: "DER SPIEGEL - Schlagzeilen",
    short: "Spiegel",
    lang: "de",
    category: "top",
    level: "hard",
    feed: "https://www.spiegel.de/schlagzeilen/tops/index.rss",
    site: "https://www.spiegel.de",
    paywall: "soft",
  },
  {
    id: "zeit",
    name: "ZEIT ONLINE",
    lang: "de",
    category: "top",
    level: "hard",
    feed: "https://newsfeed.zeit.de/index",
    site: "https://www.zeit.de",
    note: "Long, subordinate-clause-heavy prose. Excellent once you are past B2.",
    paywall: "soft",
  },
  {
    id: "faz",
    name: "FAZ - Aktuell",
    lang: "de",
    category: "top",
    level: "hard",
    feed: "https://www.faz.net/rss/aktuell/",
    site: "https://www.faz.net",
    paywall: "hard",
  },
  {
    id: "sz",
    name: "Sueddeutsche Zeitung",
    short: "SZ",
    lang: "de",
    category: "top",
    level: "hard",
    feed: "https://rss.sueddeutsche.de/rss/Topthemen",
    site: "https://www.sueddeutsche.de",
    paywall: "soft",
  },
  {
    id: "taz",
    name: "taz",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://taz.de/!p4608;rss/",
    site: "https://taz.de",
  },
  {
    id: "tagesspiegel",
    name: "Der Tagesspiegel",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://www.tagesspiegel.de/contentexport/feed/home",
    site: "https://www.tagesspiegel.de",
  },
  {
    id: "handelsblatt",
    name: "Handelsblatt",
    lang: "de",
    category: "business",
    level: "hard",
    feed: "https://www.handelsblatt.com/contentexport/feed/schlagzeilen",
    site: "https://www.handelsblatt.com",
    note: "German business daily. Dense Wirtschaftsdeutsch, ideal for finance vocabulary.",
    paywall: "hard",
  },
  {
    id: "wiwo",
    name: "WirtschaftsWoche",
    short: "WiWo",
    lang: "de",
    category: "business",
    level: "hard",
    feed: "https://www.wiwo.de/contentexport/feed/rss/schlagzeilen",
    site: "https://www.wiwo.de",
    paywall: "soft",
  },
  {
    id: "heise",
    name: "heise online",
    lang: "de",
    category: "tech",
    level: "hard",
    feed: "https://www.heise.de/rss/heise-atom.xml",
    site: "https://www.heise.de",
  },
  {
    id: "golem",
    name: "Golem.de",
    lang: "de",
    category: "tech",
    level: "medium",
    feed: "https://rss.golem.de/rss.php?feed=RSS2.0",
    site: "https://www.golem.de",
  },
  {
    id: "ndr",
    name: "NDR",
    lang: "de",
    category: "world",
    level: "medium",
    feed: "https://www.ndr.de/home/index-rss.xml",
    site: "https://www.ndr.de",
  },
  {
    id: "wdr",
    name: "WDR",
    lang: "de",
    category: "world",
    level: "medium",
    feed: "https://www1.wdr.de/uebersicht-100.feed",
    site: "https://www1.wdr.de",
  },
  {
    id: "euronews-de",
    name: "euronews (Deutsch)",
    short: "euronews DE",
    lang: "de",
    category: "world",
    level: "medium",
    feed: "https://de.euronews.com/rss",
    site: "https://de.euronews.com",
  },
  {
    id: "kicker",
    name: "kicker",
    lang: "de",
    category: "sport",
    level: "medium",
    feed: "https://newsfeed.kicker.de/news/aktuell",
    site: "https://www.kicker.de",
  },

  // ------------------------------------------- Business, strategy, research
  {
    id: "business-insider",
    name: "Business Insider",
    short: "Business Insider",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://feeds.businessinsider.com/custom/all",
    site: "https://www.businessinsider.com",
    note: "Fast-moving business and markets coverage in plain, conversational English.",
  },
  {
    id: "hbr",
    name: "Harvard Business Review",
    short: "HBR",
    lang: "en",
    category: "careers",
    level: "hard",
    feed: "https://news.google.com/rss/search?q=site:hbr.org&hl=en-US&gl=US&ceid=US:en",
    site: "https://hbr.org",
    note: "Management writing. Their own feed would not answer, so this follows them through Google News.",
    paywall: "soft",
  },

  {
    id: "sloan-review",
    name: "MIT Sloan Management Review",
    short: "MIT SMR",
    lang: "en",
    category: "business",
    level: "hard",
    feed: "https://sloanreview.mit.edu/feed/",
    site: "https://sloanreview.mit.edu",
    paywall: "hard",
  },
  {
    id: "wef",
    name: "World Economic Forum Agenda",
    short: "WEF",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://www.weforum.org/agenda/feed/",
    site: "https://www.weforum.org/agenda",
    note: "Global economy, technology and policy, written for a mixed international audience.",
  },
  {
    id: "mckinsey",
    name: "McKinsey Featured Insights",
    short: "McKinsey",
    lang: "en",
    category: "business",
    level: "hard",
    feed: "https://www.mckinsey.com/insights/rss",
    site: "https://www.mckinsey.com/featured-insights",
    note: "Consulting register: frameworks, hedged claims and a lot of nominalisation.",
  },
  {
    id: "imf-blog",
    name: "IMF Blog",
    short: "IMF",
    lang: "en",
    category: "business",
    level: "hard",
    feed: "https://www.imf.org/en/Blogs/rss",
    site: "https://www.imf.org/en/Blogs",
  },
  {
    id: "worldbank-blogs",
    name: "World Bank Blogs",
    short: "World Bank",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://blogs.worldbank.org/rss.xml",
    site: "https://blogs.worldbank.org",
  },
  {
    id: "manager-magazin",
    name: "manager magazin",
    lang: "de",
    category: "business",
    level: "hard",
    feed: "https://www.manager-magazin.de/news/index.rss",
    site: "https://www.manager-magazin.de",
    note: "German business monthly. A good bridge between Handelsblatt and SPIEGEL.",
    paywall: "soft",
  },
  {
    id: "tagesschau-wirtschaft",
    name: "tagesschau Wirtschaft",
    short: "tagesschau Wirtschaft",
    lang: "de",
    category: "business",
    level: "medium",
    feed: "https://www.tagesschau.de/wirtschaft/index~rss2.xml",
    site: "https://www.tagesschau.de/wirtschaft",
    note: "Business news in the same measured register as the main tagesschau feed.",
  },

  // --------------------------------------------------------------- English
  {
    id: "voa-learning",
    name: "VOA Learning English",
    short: "VOA Learning",
    lang: "en",
    category: "learner",
    level: "easy",
    feed: "https://news.google.com/rss/search?q=site:learningenglish.voanews.com&hl=en-US&gl=US&ceid=US:en",
    site: "https://learningenglish.voanews.com",
    note: "Written for learners, at a deliberately slower pace. Their own feed stopped returning articles, so this follows them through Google News.",
  },

  {
    id: "bbc-top",
    name: "BBC News",
    lang: "en",
    category: "top",
    level: "medium",
    feed: "https://feeds.bbci.co.uk/news/rss.xml",
    site: "https://www.bbc.com/news",
  },
  {
    id: "bbc-world",
    name: "BBC World",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://feeds.bbci.co.uk/news/world/rss.xml",
    site: "https://www.bbc.com/news/world",
  },
  {
    id: "bbc-business",
    name: "BBC Business",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://feeds.bbci.co.uk/news/business/rss.xml",
    site: "https://www.bbc.com/news/business",
  },
  {
    id: "guardian-world",
    name: "The Guardian - World",
    short: "Guardian World",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://www.theguardian.com/world/rss",
    site: "https://www.theguardian.com/world",
  },
  {
    id: "guardian-business",
    name: "The Guardian - Business",
    short: "Guardian Business",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://www.theguardian.com/uk/business/rss",
    site: "https://www.theguardian.com/business",
  },
  {
    id: "npr",
    name: "NPR News",
    lang: "en",
    category: "top",
    level: "medium",
    feed: "https://feeds.npr.org/1001/rss.xml",
    site: "https://www.npr.org",
  },
  {
    id: "aljazeera",
    name: "Al Jazeera English",
    short: "Al Jazeera",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://www.aljazeera.com/xml/rss/all.xml",
    site: "https://www.aljazeera.com",
  },
  {
    id: "nyt-home",
    name: "The New York Times",
    short: "NYT",
    lang: "en",
    category: "top",
    level: "hard",
    feed: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    site: "https://www.nytimes.com",
    paywall: "hard",
  },
  {
    id: "nyt-business",
    name: "NYT Business",
    lang: "en",
    category: "business",
    level: "hard",
    feed: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    site: "https://www.nytimes.com/section/business",
    paywall: "hard",
  },
  {
    id: "cnbc",
    name: "CNBC Top News",
    short: "CNBC",
    lang: "en",
    category: "markets",
    level: "medium",
    feed: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    site: "https://www.cnbc.com",
    note: "Markets and earnings language, useful if you work in finance.",
  },
  {
    id: "marketwatch",
    name: "MarketWatch Top Stories",
    short: "MarketWatch",
    lang: "en",
    category: "markets",
    level: "medium",
    feed: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    site: "https://www.marketwatch.com",
  },
  {
    id: "ft",
    name: "Financial Times",
    short: "FT",
    lang: "en",
    category: "business",
    level: "hard",
    feed: "https://www.ft.com/rss/home",
    site: "https://www.ft.com",
    note: "Headlines are free; full articles often sit behind the paywall.",
    paywall: "hard",
  },
  {
    id: "dw-en",
    name: "Deutsche Welle (English)",
    short: "DW English",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://rss.dw.com/rdf/rss-en-all",
    site: "https://www.dw.com/en",
    note: "The same stories as the German DW feed, which makes side-by-side reading easy.",
  },
  {
    id: "spiegel-intl",
    name: "SPIEGEL International",
    short: "Spiegel Intl",
    lang: "en",
    category: "world",
    level: "hard",
    feed: "https://www.spiegel.de/international/index.rss",
    site: "https://www.spiegel.de/international",
    note: "German reporting in English. Good for comparing register across languages.",
  },
  {
    id: "verge",
    name: "The Verge",
    lang: "en",
    category: "tech",
    level: "medium",
    feed: "https://www.theverge.com/rss/index.xml",
    site: "https://www.theverge.com",
  },
  {
    id: "ars",
    name: "Ars Technica",
    lang: "en",
    category: "tech",
    level: "hard",
    feed: "https://feeds.arstechnica.com/arstechnica/index",
    site: "https://arstechnica.com",
  },
  {
    id: "hn",
    name: "Hacker News Front Page",
    short: "Hacker News",
    lang: "en",
    category: "tech",
    level: "hard",
    feed: "https://hnrss.org/frontpage",
    site: "https://news.ycombinator.com",
  },
  {
    id: "sciencedaily",
    name: "ScienceDaily",
    lang: "en",
    category: "science",
    level: "hard",
    feed: "https://www.sciencedaily.com/rss/all.xml",
    site: "https://www.sciencedaily.com",
  },
  {
    id: "nature-news",
    name: "Nature News",
    lang: "en",
    category: "science",
    level: "hard",
    feed: "https://www.nature.com/nature.rss",
    site: "https://www.nature.com/news",
  },
  {
    id: "guardian-culture",
    name: "The Guardian - Culture",
    short: "Guardian Culture",
    lang: "en",
    category: "culture",
    level: "medium",
    feed: "https://www.theguardian.com/culture/rss",
    site: "https://www.theguardian.com/culture",
  },
  {
    id: "euronews-en",
    name: "euronews (English)",
    short: "euronews EN",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://www.euronews.com/rss",
    site: "https://www.euronews.com",
  },
  // ------------------------------------------ More sections of what you read
  {
    id: "guardian-intl",
    name: "The Guardian - International",
    short: "Guardian",
    lang: "en",
    category: "top",
    level: "medium",
    feed: "https://www.theguardian.com/international/rss",
    site: "https://www.theguardian.com/international",
    note: "The Guardian's front page. Clear, well-edited English at a fair pace.",
  },
  {
    id: "guardian-science",
    name: "The Guardian - Science",
    short: "Guardian Science",
    lang: "en",
    category: "science",
    level: "medium",
    feed: "https://www.theguardian.com/science/rss",
    site: "https://www.theguardian.com/science",
  },
  {
    id: "guardian-tech",
    name: "The Guardian - Technology",
    short: "Guardian Tech",
    lang: "en",
    category: "tech",
    level: "medium",
    feed: "https://www.theguardian.com/uk/technology/rss",
    site: "https://www.theguardian.com/technology",
  },
  {
    id: "npr-world",
    name: "NPR World",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://feeds.npr.org/1004/rss.xml",
    site: "https://www.npr.org/sections/world",
  },
  {
    id: "npr-business",
    name: "NPR Business",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://feeds.npr.org/1006/rss.xml",
    site: "https://www.npr.org/sections/business",
  },
  {
    id: "npr-science",
    name: "NPR Science",
    lang: "en",
    category: "science",
    level: "medium",
    feed: "https://feeds.npr.org/1007/rss.xml",
    site: "https://www.npr.org/sections/science",
  },
  {
    id: "politico-eu",
    name: "POLITICO Europe",
    short: "POLITICO EU",
    lang: "en",
    category: "world",
    level: "hard",
    feed: "https://www.politico.eu/feed/",
    site: "https://www.politico.eu",
    note: "Brussels politics, which is where a lot of German business news starts.",
  },
  {
    id: "wired",
    name: "WIRED",
    lang: "en",
    category: "tech",
    level: "medium",
    feed: "https://www.wired.com/feed/rss",
    site: "https://www.wired.com",
  },
  {
    id: "mit-tech-review",
    name: "MIT Technology Review",
    short: "MIT Tech Review",
    lang: "en",
    category: "tech",
    level: "hard",
    feed: "https://www.technologyreview.com/feed/",
    site: "https://www.technologyreview.com",
  },
  {
    id: "the-atlantic",
    name: "The Atlantic",
    lang: "en",
    category: "culture",
    level: "hard",
    feed: "https://www.theatlantic.com/feed/all/",
    site: "https://www.theatlantic.com",
    note: "Long-form essays. Excellent for building an abstract vocabulary.",
    paywall: "soft",
  },
  {
    id: "vox",
    name: "Vox",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://www.vox.com/rss/index.xml",
    site: "https://www.vox.com",
    note: "Explanatory journalism, so context is built into the writing.",
  },
  {
    id: "sky-world",
    name: "Sky News World",
    short: "Sky News",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://feeds.skynews.com/feeds/rss/world.xml",
    site: "https://news.sky.com/world",
  },

  // ---------------------------------------------- More of the German press
  {
    id: "welt",
    name: "WELT",
    lang: "de",
    category: "top",
    level: "hard",
    feed: "https://www.welt.de/feeds/latest.rss",
    site: "https://www.welt.de",
    paywall: "soft",
  },
  {
    id: "ntv",
    name: "n-tv",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://www.n-tv.de/rss",
    site: "https://www.n-tv.de",
    note: "Rolling news in short, plain paragraphs. Kinder to a learner than ZEIT.",
  },
  {
    id: "stern",
    name: "stern",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://www.stern.de/feed/standard/all/",
    site: "https://www.stern.de",
    note: "The feed works, but the site refuses our requests, so articles open as the feed summary.",
    paywall: "hard",
  },
  {
    id: "focus",
    name: "FOCUS online",
    short: "FOCUS",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://news.google.com/rss/search?q=site:focus.de&hl=de&gl=DE&ceid=DE:de",
    site: "https://www.focus.de",
    note: "Their own feed returned 404, so this follows them through Google News.",
  },

  {
    id: "derstandard",
    name: "DER STANDARD (Österreich)",
    short: "derStandard",
    lang: "de",
    category: "world",
    level: "hard",
    feed: "https://www.derstandard.at/rss",
    site: "https://www.derstandard.at",
    note: "Austrian German. Same language, noticeably different vocabulary.",
  },
  {
    id: "nzz",
    name: "NZZ (Schweiz)",
    short: "NZZ",
    lang: "de",
    category: "world",
    level: "hard",
    feed: "https://www.nzz.ch/recent.rss",
    site: "https://www.nzz.ch",
    note: "Swiss German press. Precise, formal, and it never uses the ß.",
    paywall: "soft",
  },
  {
    id: "spiegel-wirtschaft",
    name: "SPIEGEL Wirtschaft",
    short: "Spiegel Wirtschaft",
    lang: "de",
    category: "business",
    level: "hard",
    feed: "https://www.spiegel.de/wirtschaft/index.rss",
    site: "https://www.spiegel.de/wirtschaft",
    paywall: "soft",
  },
  {
    id: "zeit-wirtschaft",
    name: "ZEIT Wirtschaft",
    short: "ZEIT Wirtschaft",
    lang: "de",
    category: "business",
    level: "hard",
    feed: "https://newsfeed.zeit.de/wirtschaft/index",
    site: "https://www.zeit.de/wirtschaft",
    paywall: "soft",
  },
  {
    id: "dw-wissenschaft",
    name: "DW Wissenschaft",
    short: "DW Wissen",
    lang: "de",
    category: "science",
    level: "medium",
    feed: "https://rss.dw.com/xml/rss-de-wissenschaft",
    site: "https://www.dw.com/de/wissenschaft",
  },
  {
    id: "mdr",
    name: "MDR aktuell",
    short: "MDR",
    lang: "de",
    category: "world",
    level: "medium",
    feed: "https://www.mdr.de/nachrichten/index-rss.xml",
    site: "https://www.mdr.de/nachrichten",
  },
  // -------------------------------------------------------------- Việt Nam
  {
    id: "vnexpress-intl",
    name: "VnExpress International",
    short: "VnExpress Intl",
    lang: "en",
    category: "world",
    level: "easy",
    feed: "https://e.vnexpress.net/rss/news.rss",
    site: "https://e.vnexpress.net",
    note: "Vietnamese news in plain English. Familiar stories make new vocabulary much easier.",
  },
  {
    id: "vnexpress",
    name: "VnExpress",
    lang: "vi",
    category: "top",
    level: "easy",
    feed: "https://vnexpress.net/rss/tin-moi-nhat.rss",
    site: "https://vnexpress.net",
    note: "Đọc bản tiếng Việt rồi so với bản International của cùng toà soạn.",
  },
  {
    id: "vnexpress-kinhdoanh",
    name: "VnExpress Kinh doanh",
    short: "VnExpress KD",
    lang: "vi",
    category: "finance",
    level: "medium",
    feed: "https://vnexpress.net/rss/kinh-doanh.rss",
    site: "https://vnexpress.net/kinh-doanh",
  },
  {
    id: "tuoitre",
    name: "Tuổi Trẻ",
    lang: "vi",
    category: "top",
    level: "medium",
    feed: "https://tuoitre.vn/rss/tin-moi-nhat.rss",
    site: "https://tuoitre.vn",
  },
  {
    id: "thanhnien",
    name: "Thanh Niên",
    lang: "vi",
    category: "top",
    level: "medium",
    feed: "https://thanhnien.vn/rss/home.rss",
    site: "https://thanhnien.vn",
  },
  {
    id: "cafef",
    name: "CafeF",
    lang: "vi",
    category: "finance",
    level: "hard",
    feed: "https://cafef.vn/trang-chu.rss",
    site: "https://cafef.vn",
    note: "Chứng khoán và doanh nghiệp. Từ vựng tài chính tiếng Việt dày đặc.",
  },
  {
    id: "vneconomy",
    name: "VnEconomy",
    short: "VnEconomy",
    lang: "vi",
    category: "finance",
    level: "hard",
    feed: "https://news.google.com/rss/search?q=site:vneconomy.vn&hl=vi&gl=VN&ceid=VN:vi",
    site: "https://vneconomy.vn",
    note: "Their own feed answered but carried no articles, so this follows them through Google News.",
  },

  {
    id: "vietnamnews",
    name: "Việt Nam News",
    short: "VN News",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://vietnamnews.vn/rss/news.rss",
    site: "https://vietnamnews.vn",
    note: "Vietnam's English-language daily.",
  },
  {
    id: "vietnamplus-en",
    name: "VietnamPlus (English)",
    short: "VietnamPlus",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://en.vietnamplus.vn/rss/home.rss",
    site: "https://en.vietnamplus.vn",
  },

  // ------------------------------------------------ Markets, money, deals
  {
    id: "reuters-business-gn",
    name: "Reuters Business",
    short: "Reuters",
    lang: "en",
    category: "markets",
    level: "medium",
    feed: "https://news.google.com/rss/search?q=site:reuters.com+business&hl=en-US&gl=US&ceid=US:en",
    site: "https://www.reuters.com/business",
    note: "Reuters retired its public feeds, so this follows them through Google News.",
  },
  {
    id: "bloomberg-gn",
    name: "Bloomberg Markets",
    short: "Bloomberg",
    lang: "en",
    category: "markets",
    level: "hard",
    feed: "https://news.google.com/rss/search?q=site:bloomberg.com+markets&hl=en-US&gl=US&ceid=US:en",
    site: "https://www.bloomberg.com/markets",
    paywall: "hard",
  },
  {
    id: "economist-gn",
    name: "The Economist",
    short: "Economist",
    lang: "en",
    category: "finance",
    level: "hard",
    feed: "https://news.google.com/rss/search?q=site:economist.com&hl=en-US&gl=US&ceid=US:en",
    site: "https://www.economist.com",
    paywall: "hard",
    note: "Dense, allusive prose. The hardest English on the shelf, and the most rewarding.",
  },
  {
    id: "fortune",
    name: "Fortune",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://fortune.com/feed/",
    site: "https://fortune.com",
  },
  {
    id: "quartz",
    name: "Quartz",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://qz.com/rss",
    site: "https://qz.com",
  },
  {
    id: "axios-business",
    name: "Axios",
    lang: "en",
    category: "business",
    level: "easy",
    feed: "https://api.axios.com/feed/",
    site: "https://www.axios.com",
    note: "Written in deliberately short bullets. Unusually gentle for business English.",
  },
  {
    id: "finanzen-net",
    name: "finanzen.net",
    lang: "de",
    category: "markets",
    level: "hard",
    feed: "https://www.finanzen.net/rss/news",
    site: "https://www.finanzen.net",
  },

  {
    id: "capital-de",
    name: "Capital",
    short: "Capital",
    lang: "de",
    category: "finance",
    level: "hard",
    feed: "https://news.google.com/rss/search?q=site:capital.de&hl=de&gl=DE&ceid=DE:de",
    site: "https://www.capital.de",
    note: "Their own feed returned 404, so this follows them through Google News.",
    paywall: "soft",
  },

  {
    id: "business-insider-de",
    name: "Business Insider Deutschland",
    short: "BI Deutschland",
    lang: "de",
    category: "business",
    level: "medium",
    feed: "https://www.businessinsider.de/feed/businessinsider-alle-artikel",
    site: "https://www.businessinsider.de",
  },
  {
    id: "ntv-wirtschaft",
    name: "n-tv Wirtschaft",
    short: "n-tv Wirtschaft",
    lang: "de",
    category: "business",
    level: "medium",
    feed: "https://www.n-tv.de/wirtschaft/rss",
    site: "https://www.n-tv.de/wirtschaft",
    note: "Business news in short, plain sentences. A good first Wirtschaft feed.",
  },

  // ----------------------------------------------- Politics, climate, health
  {
    id: "guardian-environment",
    name: "The Guardian - Environment",
    short: "Guardian Climate",
    lang: "en",
    category: "environment",
    level: "medium",
    feed: "https://www.theguardian.com/environment/rss",
    site: "https://www.theguardian.com/environment",
  },
  {
    id: "npr-health",
    name: "NPR Health",
    lang: "en",
    category: "health",
    level: "medium",
    feed: "https://feeds.npr.org/1128/rss.xml",
    site: "https://www.npr.org/sections/health-shots",
  },
  {
    id: "bbc-politics",
    name: "BBC Politics",
    lang: "en",
    category: "politics",
    level: "medium",
    feed: "https://feeds.bbci.co.uk/news/politics/rss.xml",
    site: "https://www.bbc.com/news/politics",
  },
  {
    id: "zeit-politik",
    name: "ZEIT Politik",
    short: "ZEIT Politik",
    lang: "de",
    category: "politics",
    level: "hard",
    feed: "https://newsfeed.zeit.de/politik/index",
    site: "https://www.zeit.de/politik",
    paywall: "soft",
  },
  {
    id: "tagesschau-inland",
    name: "tagesschau Inland",
    short: "tagesschau Inland",
    lang: "de",
    category: "politics",
    level: "medium",
    feed: "https://www.tagesschau.de/inland/index~rss2.xml",
    site: "https://www.tagesschau.de/inland",
  },
  {
    id: "dw-umwelt",
    name: "DW Umwelt",
    short: "DW Umwelt",
    lang: "de",
    category: "environment",
    level: "medium",
    feed: "https://rss.dw.com/xml/rss-de-umwelt",
    site: "https://www.dw.com/de/umwelt",
  },
  {
    id: "guardian-education",
    name: "The Guardian - Education",
    short: "Guardian Education",
    lang: "en",
    category: "education",
    level: "medium",
    feed: "https://www.theguardian.com/education/rss",
    site: "https://www.theguardian.com/education",
  },
  {
    id: "bbc-education",
    name: "BBC Education",
    short: "BBC Education",
    lang: "en",
    category: "education",
    level: "medium",
    feed: "https://feeds.bbci.co.uk/news/education/rss.xml",
    site: "https://www.bbc.co.uk/news/education",
  },
  {
    id: "zeit-studium",
    name: "ZEIT Campus",
    short: "ZEIT Campus",
    lang: "de",
    category: "education",
    level: "hard",
    feed: "https://newsfeed.zeit.de/studium/index",
    site: "https://www.zeit.de/studium/index",
    note: "University life, which is the German a student actually hears.",
    paywall: "soft",
  },
  {
    id: "vnexpress-giaoduc",
    name: "VnExpress Giáo dục",
    short: "VnExpress Giáo dục",
    lang: "vi",
    category: "education",
    level: "medium",
    feed: "https://vnexpress.net/rss/giao-duc.rss",
    site: "https://vnexpress.net/giao-duc",
  },
  {
    id: "guardian-travel",
    name: "The Guardian - Travel",
    short: "Guardian Travel",
    lang: "en",
    category: "travel",
    level: "medium",
    feed: "https://www.theguardian.com/travel/rss",
    site: "https://www.theguardian.com/travel",
  },
  {
    id: "spiegel-reise",
    name: "SPIEGEL Reise",
    short: "SPIEGEL Reise",
    lang: "de",
    category: "travel",
    level: "medium",
    feed: "https://www.spiegel.de/reise/index.rss",
    site: "https://www.spiegel.de/reise",
    note: "Travel writing is gentler German than the political pages.",
    paywall: "soft",
  },
  {
    id: "vnexpress-dulich",
    name: "VnExpress Du lịch",
    short: "VnExpress Du lịch",
    lang: "vi",
    category: "travel",
    level: "easy",
    feed: "https://vnexpress.net/rss/du-lich.rss",
    site: "https://vnexpress.net/du-lich",
  },
  {
    id: "guardian-film",
    name: "The Guardian - Film",
    short: "Guardian Film",
    lang: "en",
    category: "arts",
    level: "medium",
    feed: "https://www.theguardian.com/film/rss",
    site: "https://www.theguardian.com/film",
  },
  {
    id: "guardian-books",
    name: "The Guardian - Books",
    short: "Guardian Books",
    lang: "en",
    category: "arts",
    level: "hard",
    feed: "https://www.theguardian.com/books/rss",
    site: "https://www.theguardian.com/books",
  },
  {
    id: "spiegel-kultur",
    name: "SPIEGEL Kultur",
    short: "SPIEGEL Kultur",
    lang: "de",
    category: "arts",
    level: "hard",
    feed: "https://www.spiegel.de/kultur/index.rss",
    site: "https://www.spiegel.de/kultur",
    paywall: "soft",
  },
  {
    id: "vnexpress-giaitri",
    name: "VnExpress Giải trí",
    short: "VnExpress Giải trí",
    lang: "vi",
    category: "arts",
    level: "easy",
    feed: "https://vnexpress.net/rss/giai-tri.rss",
    site: "https://vnexpress.net/giai-tri",
  },
  {
    id: "guardian-media",
    name: "The Guardian - Media",
    short: "Guardian Media",
    lang: "en",
    category: "media",
    level: "medium",
    feed: "https://www.theguardian.com/media/rss",
    site: "https://www.theguardian.com/media",
  },
  {
    id: "nieman-lab",
    name: "Nieman Journalism Lab",
    short: "Nieman Lab",
    lang: "en",
    category: "media",
    level: "medium",
    feed: "https://www.niemanlab.org/feed/",
    site: "https://www.niemanlab.org",
    note: "Where the news business writes about itself.",
  },
  {
    id: "guardian-law",
    name: "The Guardian - Law",
    short: "Guardian Law",
    lang: "en",
    category: "law",
    level: "hard",
    feed: "https://www.theguardian.com/law/rss",
    site: "https://www.theguardian.com/law",
  },
  {
    id: "lto",
    name: "Legal Tribune Online",
    short: "LTO",
    lang: "de",
    category: "law",
    level: "hard",
    feed: "https://www.lto.de/rss/feed/",
    site: "https://www.lto.de",
    note: "German legal writing, which is where the long compound nouns live.",
  },
  {
    id: "vnexpress-phapluat",
    name: "VnExpress Pháp luật",
    short: "VnExpress Pháp luật",
    lang: "vi",
    category: "law",
    level: "medium",
    feed: "https://vnexpress.net/rss/phap-luat.rss",
    site: "https://vnexpress.net/phap-luat",
  },
  {
    id: "guardian-society",
    name: "The Guardian - Society",
    short: "Guardian Society",
    lang: "en",
    category: "society",
    level: "medium",
    feed: "https://www.theguardian.com/society/rss",
    site: "https://www.theguardian.com/society",
  },
  {
    id: "spiegel-panorama",
    name: "SPIEGEL Panorama",
    short: "SPIEGEL Panorama",
    lang: "de",
    category: "society",
    level: "medium",
    feed: "https://www.spiegel.de/panorama/index.rss",
    site: "https://www.spiegel.de/panorama",
    paywall: "soft",
  },
  {
    id: "zeit-gesellschaft",
    name: "ZEIT Gesellschaft",
    short: "ZEIT Gesellschaft",
    lang: "de",
    category: "society",
    level: "hard",
    feed: "https://newsfeed.zeit.de/gesellschaft/index",
    site: "https://www.zeit.de/gesellschaft/index",
    paywall: "soft",
  },
  {
    id: "guardian-life",
    name: "The Guardian - Life and style",
    short: "Guardian Life",
    lang: "en",
    category: "lifestyle",
    level: "easy",
    feed: "https://www.theguardian.com/lifeandstyle/rss",
    site: "https://www.theguardian.com/lifeandstyle",
    note: "Short, concrete pieces about ordinary things: a kind first read.",
  },
  {
    id: "vnexpress-doisong",
    name: "VnExpress Đời sống",
    short: "VnExpress Đời sống",
    lang: "vi",
    category: "lifestyle",
    level: "easy",
    feed: "https://vnexpress.net/rss/gia-dinh.rss",
    site: "https://vnexpress.net/gia-dinh",
  },
  {
    id: "spiegel-karriere",
    name: "SPIEGEL Karriere",
    short: "SPIEGEL Karriere",
    lang: "de",
    category: "careers",
    level: "medium",
    feed: "https://www.spiegel.de/karriere/index.rss",
    site: "https://www.spiegel.de/karriere",
    note: "Work, pay and hiring: the German of a job interview.",
    paywall: "soft",
  },
  {
    id: "zeit-arbeit",
    name: "ZEIT Arbeit",
    short: "ZEIT Arbeit",
    lang: "de",
    category: "careers",
    level: "hard",
    feed: "https://newsfeed.zeit.de/arbeit/index",
    site: "https://www.zeit.de/arbeit/index",
    paywall: "soft",
  },
  {
    id: "techcrunch",
    name: "TechCrunch",
    short: "TechCrunch",
    lang: "en",
    category: "startups",
    level: "medium",
    feed: "https://techcrunch.com/feed/",
    site: "https://techcrunch.com",
  },
  {
    id: "sifted",
    name: "Sifted",
    short: "Sifted",
    lang: "en",
    category: "startups",
    level: "medium",
    feed: "https://sifted.eu/feed",
    site: "https://sifted.eu",
    note: "European startups, from the Financial Times stable.",
  },
  {
    id: "t3n",
    name: "t3n",
    short: "t3n",
    lang: "de",
    category: "startups",
    level: "medium",
    feed: "https://t3n.de/rss.xml",
    site: "https://t3n.de",
    note: "German digital business, written for people in a hurry.",
  },
  {
    id: "guardian-energy",
    name: "The Guardian - Energy",
    short: "Guardian Energy",
    lang: "en",
    category: "energy",
    level: "medium",
    feed: "https://www.theguardian.com/environment/energy/rss",
    site: "https://www.theguardian.com/environment/energy",
  },
  {
    id: "energy-gn",
    name: "Energiewende im Überblick",
    short: "Energiewende",
    lang: "de",
    category: "energy",
    level: "hard",
    feed: "https://news.google.com/rss/search?q=Energiewende+OR+Strompreis+when:7d&hl=de&gl=DE&ceid=DE:de",
    site: "https://news.google.com",
    note: "German energy policy gathered from across the press through Google News.",
  },
  {
    id: "guardian-money",
    name: "The Guardian - Money",
    short: "Guardian Money",
    lang: "en",
    category: "finance",
    level: "easy",
    feed: "https://www.theguardian.com/money/rss",
    site: "https://www.theguardian.com/money",
    note: "Personal finance in plain English, which is rarer than it should be.",
  },
  {
    id: "guardian-football",
    name: "The Guardian - Football",
    short: "Guardian Football",
    lang: "en",
    category: "sport",
    level: "medium",
    feed: "https://www.theguardian.com/football/rss",
    site: "https://www.theguardian.com/football",
  },
  {
    id: "spiegel-sport",
    name: "SPIEGEL Sport",
    short: "SPIEGEL Sport",
    lang: "de",
    category: "sport",
    level: "medium",
    feed: "https://www.spiegel.de/sport/index.rss",
    site: "https://www.spiegel.de/sport",
    paywall: "soft",
  },
  {
    id: "vnexpress-thethao",
    name: "VnExpress Thể thao",
    short: "VnExpress Thể thao",
    lang: "vi",
    category: "sport",
    level: "easy",
    feed: "https://vnexpress.net/rss/the-thao.rss",
    site: "https://vnexpress.net/the-thao",
  },
  {
    id: "vnexpress-suckhoe",
    name: "VnExpress Sức khoẻ",
    short: "VnExpress Sức khoẻ",
    lang: "vi",
    category: "health",
    level: "medium",
    feed: "https://vnexpress.net/rss/suc-khoe.rss",
    site: "https://vnexpress.net/suc-khoe",
  },
  {
    id: "spiegel-gesundheit",
    name: "SPIEGEL Gesundheit",
    short: "SPIEGEL Gesundheit",
    lang: "de",
    category: "health",
    level: "medium",
    feed: "https://www.spiegel.de/gesundheit/index.rss",
    site: "https://www.spiegel.de/gesundheit",
    paywall: "soft",
  },
  {
    id: "maerkte-gn",
    name: "Märkte und Zinsen",
    short: "Märkte",
    lang: "de",
    category: "markets",
    level: "hard",
    feed: "https://news.google.com/rss/search?q=B%C3%B6rse+OR+Aktien+OR+Zinsen+OR+Inflation+when:3d&hl=de&gl=DE&ceid=DE:de",
    site: "https://news.google.com",
    note: "German market coverage gathered from across the press, for the days the specialist feeds are quiet.",
  },
  {
    id: "tagesschau-boerse",
    name: "tagesschau Wirtschaft und Börse",
    short: "tagesschau Börse",
    lang: "de",
    category: "markets",
    level: "medium",
    feed: "https://news.google.com/rss/search?q=site:tagesschau.de+B%C3%B6rse+OR+Wirtschaft&hl=de&gl=DE&ceid=DE:de",
    site: "https://www.tagesschau.de/wirtschaft",
    note: "Public-service reporting on markets, in plainer German than the trade press.",
  },
  {
    id: "taichinh-gn",
    name: "Tài chính Việt Nam",
    short: "Tài chính VN",
    lang: "vi",
    category: "finance",
    level: "medium",
    feed: "https://news.google.com/rss/search?q=t%C3%A0i+ch%C3%ADnh+OR+ch%E1%BB%A9ng+kho%C3%A1n+OR+l%C3%A3i+su%E1%BA%A5t+when:3d&hl=vi&gl=VN&ceid=VN:vi",
    site: "https://news.google.com",
    note: "Vietnamese finance coverage gathered from across the press.",
  },

];

export const SOURCE_BY_ID = new Map(SOURCES.map((s) => [s.id, s]));

/** What a first-time visitor sees before touching any setting. */
export const DEFAULT_SOURCE_IDS = [
  "nachrichtenleicht",
  "dw-de-top",
  "tagesschau",
  "ntv",
  "zeit",
  "handelsblatt",
  "voa-learning",
  "bbc-top",
  "guardian-intl",
  "guardian-world",
  "npr",
  "cnbc",
];


export const CATEGORY_LABELS: Record<string, string> = {
  top: "Top stories",
  world: "World",
  politics: "Politics",
  business: "Business",
  finance: "Finance",
  markets: "Markets",
  startups: "Startups",
  careers: "Work & careers",
  tech: "Technology",
  science: "Science",
  health: "Health",
  environment: "Climate",
  energy: "Energy",
  culture: "Culture",
  arts: "Film, books & music",
  media: "Media",
  education: "Education",
  law: "Law",
  society: "Society",
  lifestyle: "Life",
  travel: "Travel",
  opinion: "Opinion",
  sport: "Sport",
  learner: "For learners",
};

export const LANG_LABELS: Record<string, string> = {
  de: "Deutsch",
  en: "English",
  vi: "Tiếng Việt",
};

export const LEVEL_LABELS: Record<string, string> = {
  easy: "Easy",
  medium: "Medium",
  hard: "Advanced",
};
