import type { Source } from "./types";

/**
 * The newsstand shelf.
 *
 * Feed URLs move around more often than publishers admit, so every entry is
 * checked by `npm run check:sources` and the feed API quietly skips whatever is
 * down rather than failing the whole page. `level` is a reading-difficulty hint
 * for learners, not a judgement on the journalism.
 */
export const SOURCES: Source[] = [
  // ---------------------------------------------------------------- German
  {
    id: "nachrichtenleicht",
    name: "Nachrichtenleicht (Deutschlandfunk)",
    short: "Nachrichtenleicht",
    lang: "de",
    category: "learner",
    level: "easy",
    feed: "https://www.nachrichtenleicht.de/nachrichtenleicht-nachrichten-100.rss",
    site: "https://www.nachrichtenleicht.de",
    note: "News in Leichte Sprache: short sentences, one idea per line. The best starting point for A2 to B1.",
  },
  {
    id: "dw-de-top",
    name: "Deutsche Welle - Top-Themen",
    short: "DW Top",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://rss.dw.com/xml/rss-de-top",
    site: "https://www.dw.com/de",
    note: "Written for an international audience, so the vocabulary stays fair.",
  },
  {
    id: "dw-de-all",
    name: "Deutsche Welle - Alle Themen",
    short: "DW Alle",
    lang: "de",
    category: "world",
    level: "medium",
    feed: "https://rss.dw.com/rdf/rss-de-all",
    site: "https://www.dw.com/de",
  },
  {
    id: "tagesschau",
    name: "tagesschau",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://www.tagesschau.de/xml/rss2/",
    site: "https://www.tagesschau.de",
    note: "Germany's reference newscast. Clean, factual register.",
  },
  {
    id: "zdf-heute",
    name: "ZDF heute",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://www.zdf.de/rss/zdf/nachrichten",
    site: "https://www.zdf.de/nachrichten",
  },
  {
    id: "deutschlandfunk",
    name: "Deutschlandfunk Nachrichten",
    short: "DLF",
    lang: "de",
    category: "top",
    level: "hard",
    feed: "https://www.deutschlandfunk.de/nachrichten-100.rss",
    site: "https://www.deutschlandfunk.de",
  },
  {
    id: "spiegel",
    name: "DER SPIEGEL - Schlagzeilen",
    short: "Spiegel",
    lang: "de",
    category: "top",
    level: "hard",
    feed: "https://www.spiegel.de/schlagzeilen/tops/index.rss",
    site: "https://www.spiegel.de",
  },
  {
    id: "zeit",
    name: "ZEIT ONLINE",
    lang: "de",
    category: "top",
    level: "hard",
    feed: "https://newsfeed.zeit.de/index",
    site: "https://www.zeit.de",
    note: "Long, subordinate-clause-heavy prose. Excellent once you are past B2.",
  },
  {
    id: "faz",
    name: "FAZ - Aktuell",
    lang: "de",
    category: "top",
    level: "hard",
    feed: "https://www.faz.net/rss/aktuell/",
    site: "https://www.faz.net",
  },
  {
    id: "sz",
    name: "Sueddeutsche Zeitung",
    short: "SZ",
    lang: "de",
    category: "top",
    level: "hard",
    feed: "https://rss.sueddeutsche.de/rss/Topthemen",
    site: "https://www.sueddeutsche.de",
  },
  {
    id: "taz",
    name: "taz",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://taz.de/!p4608;rss/",
    site: "https://taz.de",
  },
  {
    id: "tagesspiegel",
    name: "Der Tagesspiegel",
    lang: "de",
    category: "top",
    level: "medium",
    feed: "https://www.tagesspiegel.de/contentexport/feed/home",
    site: "https://www.tagesspiegel.de",
  },
  {
    id: "handelsblatt",
    name: "Handelsblatt",
    lang: "de",
    category: "business",
    level: "hard",
    feed: "https://www.handelsblatt.com/contentexport/feed/schlagzeilen",
    site: "https://www.handelsblatt.com",
    note: "German business daily. Dense Wirtschaftsdeutsch, ideal for finance vocabulary.",
  },
  {
    id: "wiwo",
    name: "WirtschaftsWoche",
    short: "WiWo",
    lang: "de",
    category: "business",
    level: "hard",
    feed: "https://www.wiwo.de/contentexport/feed/rss/schlagzeilen",
    site: "https://www.wiwo.de",
  },
  {
    id: "heise",
    name: "heise online",
    lang: "de",
    category: "tech",
    level: "hard",
    feed: "https://www.heise.de/rss/heise-atom.xml",
    site: "https://www.heise.de",
  },
  {
    id: "golem",
    name: "Golem.de",
    lang: "de",
    category: "tech",
    level: "medium",
    feed: "https://rss.golem.de/rss.php?feed=RSS2.0",
    site: "https://www.golem.de",
  },
  {
    id: "ndr",
    name: "NDR",
    lang: "de",
    category: "world",
    level: "medium",
    feed: "https://www.ndr.de/home/index-rss.xml",
    site: "https://www.ndr.de",
  },
  {
    id: "wdr",
    name: "WDR",
    lang: "de",
    category: "world",
    level: "medium",
    feed: "https://www1.wdr.de/uebersicht-100.feed",
    site: "https://www1.wdr.de",
  },
  {
    id: "euronews-de",
    name: "euronews (Deutsch)",
    short: "euronews DE",
    lang: "de",
    category: "world",
    level: "medium",
    feed: "https://de.euronews.com/rss",
    site: "https://de.euronews.com",
  },
  {
    id: "kicker",
    name: "kicker",
    lang: "de",
    category: "sport",
    level: "medium",
    feed: "https://newsfeed.kicker.de/news/aktuell",
    site: "https://www.kicker.de",
  },

  // ------------------------------------------- Business, strategy, research
  {
    id: "business-insider",
    name: "Business Insider",
    short: "Business Insider",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://feeds.businessinsider.com/custom/all",
    site: "https://www.businessinsider.com",
    note: "Fast-moving business and markets coverage in plain, conversational English.",
  },
  {
    id: "hbr",
    name: "Harvard Business Review",
    short: "HBR",
    lang: "en",
    category: "business",
    level: "hard",
    feed: "https://feeds.hbr.org/harvardbusiness",
    site: "https://hbr.org",
    note: "Management thinking at length. Dense, but the vocabulary is worth the effort.",
  },
  {
    id: "sloan-review",
    name: "MIT Sloan Management Review",
    short: "MIT SMR",
    lang: "en",
    category: "business",
    level: "hard",
    feed: "https://sloanreview.mit.edu/feed/",
    site: "https://sloanreview.mit.edu",
  },
  {
    id: "wef",
    name: "World Economic Forum Agenda",
    short: "WEF",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://www.weforum.org/agenda/feed/",
    site: "https://www.weforum.org/agenda",
    note: "Global economy, technology and policy, written for a mixed international audience.",
  },
  {
    id: "mckinsey",
    name: "McKinsey Featured Insights",
    short: "McKinsey",
    lang: "en",
    category: "business",
    level: "hard",
    feed: "https://www.mckinsey.com/insights/rss",
    site: "https://www.mckinsey.com/featured-insights",
    note: "Consulting register: frameworks, hedged claims and a lot of nominalisation.",
  },
  {
    id: "imf-blog",
    name: "IMF Blog",
    short: "IMF",
    lang: "en",
    category: "business",
    level: "hard",
    feed: "https://www.imf.org/en/Blogs/rss",
    site: "https://www.imf.org/en/Blogs",
  },
  {
    id: "worldbank-blogs",
    name: "World Bank Blogs",
    short: "World Bank",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://blogs.worldbank.org/rss.xml",
    site: "https://blogs.worldbank.org",
  },
  {
    id: "manager-magazin",
    name: "manager magazin",
    lang: "de",
    category: "business",
    level: "hard",
    feed: "https://www.manager-magazin.de/news/index.rss",
    site: "https://www.manager-magazin.de",
    note: "German business monthly. A good bridge between Handelsblatt and SPIEGEL.",
  },
  {
    id: "tagesschau-wirtschaft",
    name: "tagesschau Wirtschaft",
    short: "tagesschau Wirtschaft",
    lang: "de",
    category: "business",
    level: "medium",
    feed: "https://www.tagesschau.de/wirtschaft/index~rss2.xml",
    site: "https://www.tagesschau.de/wirtschaft",
    note: "Business news in the same measured register as the main tagesschau feed.",
  },

  // --------------------------------------------------------------- English
  {
    id: "voa-learning",
    name: "VOA Learning English",
    short: "VOA Learning",
    lang: "en",
    category: "learner",
    level: "easy",
    feed: "https://learningenglish.voanews.com/api/zkvymeuiim",
    site: "https://learningenglish.voanews.com",
    note: "Deliberately simplified English at a slower pace. Pairs well with Nachrichtenleicht.",
  },
  {
    id: "bbc-top",
    name: "BBC News",
    lang: "en",
    category: "top",
    level: "medium",
    feed: "https://feeds.bbci.co.uk/news/rss.xml",
    site: "https://www.bbc.com/news",
  },
  {
    id: "bbc-world",
    name: "BBC World",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://feeds.bbci.co.uk/news/world/rss.xml",
    site: "https://www.bbc.com/news/world",
  },
  {
    id: "bbc-business",
    name: "BBC Business",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://feeds.bbci.co.uk/news/business/rss.xml",
    site: "https://www.bbc.com/news/business",
  },
  {
    id: "guardian-world",
    name: "The Guardian - World",
    short: "Guardian World",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://www.theguardian.com/world/rss",
    site: "https://www.theguardian.com/world",
  },
  {
    id: "guardian-business",
    name: "The Guardian - Business",
    short: "Guardian Business",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://www.theguardian.com/uk/business/rss",
    site: "https://www.theguardian.com/business",
  },
  {
    id: "npr",
    name: "NPR News",
    lang: "en",
    category: "top",
    level: "medium",
    feed: "https://feeds.npr.org/1001/rss.xml",
    site: "https://www.npr.org",
  },
  {
    id: "aljazeera",
    name: "Al Jazeera English",
    short: "Al Jazeera",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://www.aljazeera.com/xml/rss/all.xml",
    site: "https://www.aljazeera.com",
  },
  {
    id: "nyt-home",
    name: "The New York Times",
    short: "NYT",
    lang: "en",
    category: "top",
    level: "hard",
    feed: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml",
    site: "https://www.nytimes.com",
  },
  {
    id: "nyt-business",
    name: "NYT Business",
    lang: "en",
    category: "business",
    level: "hard",
    feed: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    site: "https://www.nytimes.com/section/business",
  },
  {
    id: "cnbc",
    name: "CNBC Top News",
    short: "CNBC",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    site: "https://www.cnbc.com",
    note: "Markets and earnings language, useful if you work in finance.",
  },
  {
    id: "marketwatch",
    name: "MarketWatch Top Stories",
    short: "MarketWatch",
    lang: "en",
    category: "business",
    level: "medium",
    feed: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    site: "https://www.marketwatch.com",
  },
  {
    id: "ft",
    name: "Financial Times",
    short: "FT",
    lang: "en",
    category: "business",
    level: "hard",
    feed: "https://www.ft.com/rss/home",
    site: "https://www.ft.com",
    note: "Headlines are free; full articles often sit behind the paywall.",
  },
  {
    id: "dw-en",
    name: "Deutsche Welle (English)",
    short: "DW English",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://rss.dw.com/rdf/rss-en-all",
    site: "https://www.dw.com/en",
    note: "The same stories as the German DW feed, which makes side-by-side reading easy.",
  },
  {
    id: "spiegel-intl",
    name: "SPIEGEL International",
    short: "Spiegel Intl",
    lang: "en",
    category: "world",
    level: "hard",
    feed: "https://www.spiegel.de/international/index.rss",
    site: "https://www.spiegel.de/international",
    note: "German reporting in English. Good for comparing register across languages.",
  },
  {
    id: "verge",
    name: "The Verge",
    lang: "en",
    category: "tech",
    level: "medium",
    feed: "https://www.theverge.com/rss/index.xml",
    site: "https://www.theverge.com",
  },
  {
    id: "ars",
    name: "Ars Technica",
    lang: "en",
    category: "tech",
    level: "hard",
    feed: "https://feeds.arstechnica.com/arstechnica/index",
    site: "https://arstechnica.com",
  },
  {
    id: "hn",
    name: "Hacker News Front Page",
    short: "Hacker News",
    lang: "en",
    category: "tech",
    level: "hard",
    feed: "https://hnrss.org/frontpage",
    site: "https://news.ycombinator.com",
  },
  {
    id: "sciencedaily",
    name: "ScienceDaily",
    lang: "en",
    category: "science",
    level: "hard",
    feed: "https://www.sciencedaily.com/rss/all.xml",
    site: "https://www.sciencedaily.com",
  },
  {
    id: "nature-news",
    name: "Nature News",
    lang: "en",
    category: "science",
    level: "hard",
    feed: "https://www.nature.com/nature.rss",
    site: "https://www.nature.com/news",
  },
  {
    id: "guardian-culture",
    name: "The Guardian - Culture",
    short: "Guardian Culture",
    lang: "en",
    category: "culture",
    level: "medium",
    feed: "https://www.theguardian.com/culture/rss",
    site: "https://www.theguardian.com/culture",
  },
  {
    id: "euronews-en",
    name: "euronews (English)",
    short: "euronews EN",
    lang: "en",
    category: "world",
    level: "medium",
    feed: "https://www.euronews.com/rss",
    site: "https://www.euronews.com",
  },
];

export const SOURCE_BY_ID = new Map(SOURCES.map((s) => [s.id, s]));

/** What a first-time visitor sees before touching any setting. */
export const DEFAULT_SOURCE_IDS = [
  "nachrichtenleicht",
  "dw-de-top",
  "tagesschau",
  "zeit",
  "handelsblatt",
  "voa-learning",
  "bbc-top",
  "guardian-world",
  "npr",
  "cnbc",
];

export const CATEGORY_LABELS: Record<string, string> = {
  top: "Top stories",
  world: "World",
  business: "Business",
  tech: "Technology",
  science: "Science",
  culture: "Culture",
  sport: "Sport",
  learner: "For learners",
};

export const LEVEL_LABELS: Record<string, string> = {
  easy: "Easy",
  medium: "Medium",
  hard: "Advanced",
};
